name: build

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: takuyaohashi/setup-flutter@v1
        with:
          flutter-version: 'v1.12.13+hotfix.5'
          channel: 'stable'
      - run: flutter test